-- 添加 SEO 相关字段
ALTER TABLE links ADD COLUMN IF NOT EXISTS seoPriority INT DEFAULT 80;
ALTER TABLE links ADD COLUMN IF NOT EXISTS noIndex INT DEFAULT 0;
ALTER TABLE links ADD COLUMN IF NOT EXISTS redirectType VARCHAR(10) DEFAULT '302';
ALTER TABLE links ADD COLUMN IF NOT EXISTS seoKeywords TEXT;
ALTER TABLE links ADD COLUMN IF NOT EXISTS canonicalUrl VARCHAR(500);
ALTER TABLE links ADD COLUMN IF NOT EXISTS ogVideoUrl TEXT;
ALTER TABLE links ADD COLUMN IF NOT EXISTS ogVideoWidth INT DEFAULT 1200;
ALTER TABLE links ADD COLUMN IF NOT EXISTS ogVideoHeight INT DEFAULT 630;
