/**
 * Backend Error Codes
 *
 * These error codes are used in the backend and translated in the frontend.
 * Format: ERROR_MODULE_SPECIFIC (e.g., AUTH_INVALID_CREDENTIALS)
 */

export const ErrorCodes = {
  // Authentication errors (AUTH_*)
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_USERNAME_EXISTS: "AUTH_USERNAME_EXISTS",
  AUTH_USERNAME_FORMAT: "AUTH_USERNAME_FORMAT",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_PASSWORD_INCORRECT: "AUTH_PASSWORD_INCORRECT",

  // Authorization errors (FORBIDDEN_*)
  FORBIDDEN_NO_USER: "FORBIDDEN_NO_USER",
  FORBIDDEN_DOMAIN_NOT_OWNED: "FORBIDDEN_DOMAIN_NOT_OWNED",
  FORBIDDEN_DOMAIN_NOT_VERIFIED: "FORBIDDEN_DOMAIN_NOT_VERIFIED",

  // Link errors (LINK_*)
  LINK_NOT_FOUND: "LINK_NOT_FOUND",
  LINK_SHORT_CODE_EXISTS: "LINK_SHORT_CODE_EXISTS",
  LINK_SHORT_CODE_DOMAIN_EXISTS: "LINK_SHORT_CODE_DOMAIN_EXISTS",
  LINK_INACTIVE: "LINK_INACTIVE",
  LINK_NOT_PASSWORD_PROTECTED: "LINK_NOT_PASSWORD_PROTECTED",

  // Domain errors (DOMAIN_*)
  DOMAIN_NOT_FOUND: "DOMAIN_NOT_FOUND",
  DOMAIN_ALREADY_REGISTERED: "DOMAIN_ALREADY_REGISTERED",

  // Security errors (SECURITY_*)
  SECURITY_TOKEN_INVALID: "SECURITY_TOKEN_INVALID",
  SECURITY_TOKEN_EXPIRED: "SECURITY_TOKEN_EXPIRED",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
